/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 logo.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.01, 2.97, -0.46]} rotation={[Math.PI / 2, -0.04, 0]} scale={4.6}>
        <mesh geometry={nodes.Plane010.geometry} material={materials.amblem} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/logo-transformed.glb')
